apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-dev
  annotations:
    argocd.argoproj.io/sync-wave: "20"  
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: bolauder88@gmail.com
    # This key doesn't exist, cert-manager creates it
    privateKeySecretRef:
      name: dev-letsencrypt-issuer-account-key
    solvers:
    - dns01:
        route53:
#         hostedZoneID: Z2FSPBG485WLBI
         hostedZoneID: Z06649973UKIFVPH1Q9HI
         region: us-east-2
         secretAccessKeySecretRef:
           name: ''
