---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-openshift-routes
  namespace: cert-manager
  labels:
    app.kubernetes.io/name: cert-manager-openshift-routes
    app.kubernetes.io/version: "0.5.0"
    app.kubernetes.io/component: controller
    app.kubernetes.io/part-of: cert-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: cert-manager-openshift-routes
      app.kubernetes.io/version: "0.5.0"
      app.kubernetes.io/component: controller
      app.kubernetes.io/part-of: cert-manager
  template:
    metadata:
      labels:
        app.kubernetes.io/name: cert-manager-openshift-routes
        app.kubernetes.io/version: "0.5.0"
        app.kubernetes.io/component: controller
        app.kubernetes.io/part-of: cert-manager
    spec:
      serviceAccountName: cert-manager-openshift-routes
      automountServiceAccountToken: true
      containers:
        - name: cert-manager-openshift-routes
          image: "ghcr.io/cert-manager/cert-manager-openshift-routes:0.5.0"
          args:
          - -v=5
          ports:
          - containerPort: 6060
            name: readiness
            protocol: TCP
          - containerPort: 9402
            name: metrics
            protocol: TCP
          readinessProbe:
            httpGet:
              port: readiness
              path: "/readyz"
            initialDelaySeconds: 3
            periodSeconds: 5
            timeoutSeconds: 3