apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Subscription
      name: web-terminal
    patch: |-
      - op: replace
        path: /spec/channel
        value: fast

  - path: exclude-default-template.yaml


