---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
#  - ../../base
# This is the correct order of creation
  - cloudstorage.yaml
  - backupstoragelocation.yaml
  - dpa.yaml
