---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-v1'
      - op: replace
        path: /spec/config/env/0/value
        value: 'arn:aws:iam::942823120101:role/bosez-20240710-cert-manager-operator'        
    target:
      group: operators.coreos.com
      kind: Subscription
      name: openshift-cert-manager-operator
      namespace: cert-manager-operator
      version: v1alpha1

