---
# Commented out values not likely to change

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: ecm-uat

resources:
  - ../../base
  # - secretproviderclass.yaml # Remove this when moving to External Secrets Operator
  - secretstore.yaml
  - namespace.yaml
  - externalsecret-db_string.yaml  
  

patches:
  - target:
      version: v1
      kind: ServiceAccount
      name: PATCH-ME # This is a placeholder and will be replaced with the value below.
    patch: |-
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::xxxxxxxxxxxxxx:role/xxxx-cwisrosa-d-ecm-sa-role
      - op: replace
        path: /metadata/namespace
        value: ecm-uat
      - op: replace
        path: /metadata/name
        value: iam-app-s3-sa-uat

  - target:
      kind: Deployment
      name: ecm
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: ecm-uat
      - op: replace
        path: /spec/replicas
        value: 1
      - op: replace
        path: /spec/template/spec/containers/0/image
        value: xxxxxxxxxxxxxx.dkr.ecr.us-east-1.amazonaws.com/cwisrosa-d-ecm:latest
      - op: replace
        path: /spec/template/spec/containers/0/env/0/valueFrom/secretKeyRef/name
        value: ecm-uat-aws-secrets
      # - op: replace
      #   path: /spec/template/spec/containers/0/volumeMounts/0/name
      #   value: ecm-uat-aws-secrets
      # - op: replace
      #   path: /spec/template/spec/volumes/0/csi/volumeAttributes/secretProviderClass
      #   value: ecm-uat-aws-secrets
      # - op: replace
      #   path: /spec/template/spec/volumes/0/name
      #   value: ecm-uat-aws-secrets
      - op: replace
        path: /spec/template/spec/serviceAccount
        value: iam-app-s3-sa-uat
      - op: replace
        path: /spec/template/spec/serviceAccountName
        value: iam-app-s3-sa-uat
      # - op: replace
      #   path: /spec/template/spec/containers/0/ports/containerPort
      #   value: 8000
      # - op: replace
      #   path: /spec/template/spec/containers/0/volumeMounts/0/mountPath
      #   value: /mnt/secrets-store

  - target:
      kind: Service
      name: ecm-service
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: ecm-uat
      - op: replace
        path: /spec/ports/0/nodePort
        value: 30020
      # - op: replace
      #   path: /spec/ports/0/port
      #   value: 80
      # - op: replace
      #   path: /spec/ports/0/targetPort
      #   value: 8000

  - target:
      kind: Route
      name: ecm-route
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: ecm-uat

  - target:
      kind: ServiceAccount
      name: external-secrets-operator-sa
    patch: |-
      - op: replace
        path: /metadata/namespace
        value: ecm-uat
      - op: replace
        path: /metadata/annotations/eks.amazonaws.com~1role-arn
        value: arn:aws:iam::xxxxxxxxxxxxxx:role/xxxx-cwisrosa-d-ecm-sa-role

  # - target:
  #     kind: ExternalSecret
  #     name: db-string
  #   patch: |-
  #     - op: replace
  #       path: /spec/secretStoreRef/name
  #       value: ecm-uat-aws-secrets
  #     - op: replace
  #       path: /spec/target/name
  #       value: db_string
  #     - op: replace
  #       path: /spec/data/0/secretKey
  #       value: db_string
  #     - op: replace
  #       path: /spec/data/0/remoteRef/key
  #       value: xxxx-cwisrosa-d-ecm-sit-1
  #     - op: replace
  #       path: /spec/data/0/remoteRef/property
  #       value: db_string



