apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: swagger
  namespace: ocp-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: swagger
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: day2/manifests/swagger
    repoURL: https://github.com/mmwillingham/iac
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true