apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-deployment
  labels:
    app: swagger
    owner: sbraman
spec:
  replicas: 2
  selector:
    matchLabels:
      app: swagger
      owner: sbraman
  template:
    metadata:          
      labels:
        app: swagger
        owner: sbraman
    spec:
      restartPolicy: Always
      containers: 
      - name: swagger
        image: "quay.io/sbraman/swagger-openshift:v1"
        imagePullPolicy: Always
        resources:
          requests:
            memory: "100Mi"
            cpu: "200m"
          limits:
            memory: "200Mi"
            cpu: "300m"
        env:
        - name: BASE_URL          
          value: "/swagger"
        - name: SWAGGER_JSON
          value: "/ocp-4-11-0.json"
        ports:
        - containerPort: 8080
        readinessProbe:
          exec:
            command:
            - cat
            - /etc/hosts
          initialDelaySeconds: 5  
        livenessProbe:
          exec:
            command:
            - cat
            - /etc/hosts
          initialDelaySeconds: 5