apiVersion: v1
kind: Service
metadata:
  name: swagger-service  
  labels:
    app: swagger
    owner: sbraman
spec:
  type: ClusterIP
  selector:
    app: swagger
  ports:
  - name: swagger
    protocol: TCP
    port: 9080
    targetPort: 8080