apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: app-day2
  namespace: ocp-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: day2/apps
    repoURL: https://github.com/mmwillingham/iac
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true