# apiVersion: argoproj.io/v1alpha1
# kind: AppProject
# metadata:
#   name: default-app-roject
#   namespace: ocp-gitops
# spec:
#   clusterResourceWhitelist:
#     - group: '*'
#       kind: '*'
#   destinations:
#     - namespace: '*'
#       server: '*'
#   sourceRepos:
#     - '*'