apiVersion: v1
kind: Namespace
metadata:
  name: ocp-gitops
  annotations:
    argocd.argoproj.io/sync-wave: "1" # (1)
# ---
# apiVersion: operators.coreos.com/v1alpha1
# kind: Subscription
# metadata:
#   name: openshift-gitops-operator
#   namespace: ocp-gitops
#   annotations:
#     argocd.argoproj.io/sync-wave: "2" # (2)
# spec:
#   channel: latest
#   installPlanApproval: Automatic
#   name: openshift-gitops-operator
#   source: redhat-operators
#   sourceNamespace: openshift-marketplace
# ---
# apiVersion: operators.coreos.com/v1alpha2
# kind: OperatorGroup
# metadata:
#   name: gitops-og
#   namespace: ocp-gitops
#   annotations:
#     argocd.argoproj.io/sync-wave: "2" # (2)
# spec: {}
# ...