apiVersion: v1
kind: Namespace
metadata:
  name: ocp-gitops
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-gitops-operator
  namespace: ocp-gitops
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  # config:
  #   env:
  #     name: "DISABLE_DEFAULT_ARGOCD_INSTANCE"
  #     value: "true"
---
apiVersion: operators.coreos.com/v1alpha2
kind: OperatorGroup
metadata:
  name: gitops-og
  namespace: ocp-gitops
spec: {}
...