kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: spe-volume-claim
  namespace: spe
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: spe-storage
  volumeMode: Filesystem
