apiVersion: external-secrets.io/v1beta1
kind: SecretStore
metadata:
  name: mystore
spec:
  provider:
    aws:
      service: SecretsManager
      region: PATCH-ME
      auth:
        jwt:
          serviceAccountRef:
            name: external-secrets-operator-sa