apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: kube-ops-view
  namespace: openshift-gitops
  labels:
    appgrp: day2
  # finalizers:
  # - resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    path: openshift-automation/day2/kustomize/kube-ops-view/overlays/default
    repoURL: https://github.com/mmwillingham/iac
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
