---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - target:
      kind: Secret
      name: rtf-pull-secret
    patch: |-
      - op: replace
        path: data/dockerconfigjson
        value: "$IMAGE_PULL_SECRET"
        
