apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: default-app-roject
  namespace: openshift-gitops-operator
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'