apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-operator-sa
  namespace: PATCH-ME
  labels:
    app.kubernetes.io/name: vault-app-nc
  annotations:
    eks.amazonaws.com/role-arn: 'PATCH-ME'