---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patches:
  - patch: |-
      - op: replace
        path: /spec/channel
        value: 'stable-1.4'
      - op: replace
        path: /spec/config/env/0/value
        value: 'arn:aws:iam::942823120101:role/bosez-20240710-openshift-oadp-aws-cloud-credentials'        
    target:
      group: operators.coreos.com
      kind: Subscription
      name: redhat-oadp-operator
      namespace: openshift-adp
      version: v1alpha1

