apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ecm-dev-aws-secrets
  namespace: ecm-dev
spec:
  provider: aws
  secretObjects:
  - data:
    - key: db_string
      objectName: dhhs-cwisrosa-d-ecm-dev-1
    secretName: ecm-dev-aws-secrets
    type: Opaque
  parameters:
    objects: |
      - objectName: dhhs-cwisrosa-d-ecm-dev-1
        objectType: "secretsmanager"