---
# Commented out values not likely to change

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# patches:
#   - target:
#       version: v1
#       kind: ServiceAccount
#       name: 
#     patch: |-
#       - op: replace
#         path: 
#         value: 
