---
apiVersion: v1
kind: Namespace
metadata:
  name: swagger-demo
  labels:
    argocd.argoproj.io/managed-by: ocp-gitops
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:  
  name: demo-apps
  namespace: ocp-gitops
  labels:
    appgrp: demo-apps  
spec:
  destinations:
    - namespace: swagger-demo      
      server: 'https://kubernetes.default.svc'
  sourceRepos:
    - 'https://gsbraman.github.io/stp/'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: swagger
  namespace: ocp-gitops
  labels:
    appgrp: demo-apps  
spec:
  project: demo-apps
  source:
    repoURL: https://gsbraman.github.io/stp/    
    chart: swagger
    targetRevision: 7.0.3  # chart version
    # override default values in values.yaml
    helm:
      values: |        
        containerLimitsCpu: "400m"
        containerLimitsMemory: "300Mi"       
  destination:    
    server: https://kubernetes.default.svc
    namespace: swagger-demo
  syncPolicy:
    automated:
      selfHeal: true
...