apiVersion: operator.openshift.io/v1
kind: IngressController
metadata:
  name: extapps-ingress
  namespace: openshift-ingress-operator
spec:
  clientTLS:
    clientCA:
      name: ''
    clientCertificatePolicy: ''
  domain: PATCH-ME
  defaultCertificate:
    name: PATCH-ME
  endpointPublishingStrategy:
    type: LoadBalancerService
    loadBalancer:
      scope: External
      providerParameters:
        type: AWS
        aws:
          type: NLB
  httpCompression: {}
  httpEmptyRequestsPolicy: Respond
  httpErrorCodePages:
    name: ''
  tuningOptions:
    reloadInterval: 0s
  unsupportedConfigOverrides: null          