kind: Subscription
apiVersion: operators.coreos.com/v1alpha1
metadata:
  name: openshift-gitops
  namespace: openshift-operators
spec:
  channel: latest
  installPlanApproval: Automatic
  name: openshift-gitops-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace