apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: ecm-uat-aws-secrets
  namespace: ecm-uat
spec:
  provider: aws
  secretObjects:
  - data:
    - key: db_string
      objectName: dhhs-cwisrosa-d-ecm-sit-1
    secretName: ecm-uat-aws-secrets
    type: Opaque
  parameters:
    objects: |
      - objectName: dhhs-cwisrosa-d-ecm-sit-1
        objectType: "secretsmanager"