apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:  
  name: hello-world-bg
  namespace: openshift-gitops
  labels:
    appgrp: day2
  finalizers:
  - resources-finalizer.argocd.argoproj.io  
spec:
  destination:    
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: false
    path: openshift-automation/day_2/kustomize/hello-world-bg/overlays/base
    repoURL: https://github.com/mmwillingham/iac.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true